name: Run Python Script

on:
  repository_dispatch:
    types: [run-hello-world]

permissions:
  contents: read

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Run Python script
      run: |
        python scripts/main.py \
        --email-address-reporter "${{ github.event.client_payload.emailAddressReporter }}" \
        --email-address-other "${{ github.event.client_payload.emailAddressOther }}" \
        --access-for "${{ github.event.client_payload.accessFor }}" \
        --requested-okta-groups "${{ github.event.client_payload.requestedOktaGroups }}" \
        --asset-messages "${{ github.event.client_payload.asset_messages }}" \
        --accesstype "${{ github.event.client_payload.accesstype }}" \
        --requested-custom-groups "${{ github.event.client_payload.requestedCustomGroups }}" \
        --issue-key "${{ github.event.client_payload.issueKey }}"
