name: Access Request Script

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  # Uncomment the lines below if you want to trigger based on issue or schedule
  # issues:
  #   types: [opened, edited]
  # schedule:
  #   - cron: '30 3 * * *'  # Adjust your schedule as needed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Run the script
      env:
        OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        KID: ${{ secrets.KID }}
        JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
        JIRA_AUTH_TOKEN: ${{ secrets.JIRA_AUTH_TOKEN }}
      run: python scripts/main.py
